### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by hanjunwei-lab** [YeoLab/repetitive-element-mapping#1]
Hello，
I read the process of`repetitive-element-mapping` and related papers, but I still have two questions that are not clear.
1. In the `repetitive-element-mapping` module, only `repeat-mapping-hg19-refdata` is provided. If I want to do mouse data, how can I collect repeat-mapping reference data? Is there a more detailed description?
2. I ran the'repetitive-element-mapping' program. In the result, what do `preRmDup.sam.gz` and `RmDup.sam.gz` mean? Which file should be used for subsequent Calls peaks, Input normalization and IDR analysis?
Looking forward to your reply，
Thank!

**Comment by byee4** [comment]
1. I've uploaded an example set of reference data for GRCh38, unfortunately we do not have a reference for mice at the moment, however you can look at the publication referenced here: [https://doi.org/10.1186/s13059-020-01982-9](https://doi.org/10.1186/s13059-020-01982-9) for a more detailed description of how these files were made.
2. the preRmDup.sam.gz is a gzipped file corresponding to reads mapping to either genome or repeat families, prior to collapsing duplicates. They are intermediates typically used for debugging and things like that. RmDup.sam.gz files are post-collapsing, so if you wanted to dig into where the reads map, the RmDup.sam.gz files would be more useful.
